# Generated by Django 4.2.4 on 2023-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='xyz@mail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='newuser', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(default='userx', max_length=12),
        ),
    ]
