# Generated by Django 4.2.4 on 2023-08-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_userprofile_email_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
    ]
